### ISSUE TITLE
Doesn't seem to work with recent versions of GHC

### ISSUE THREAD

**Issue by erlandsona** [j-mie6/ParsleyHaskell#54]
Had an idea for a language I wanted to use Parsley for but just bootstrapping a project with stack & GHC 9.4.5 and doesn't seem like it's up to date?

Curious how I should proceed?
- Fork and try and bump the versions or "just use an older GHC" maybe?
- Use another parsing library maybe newer/older? (any recommendations / things to avoid in particular)?

I watched you're talks and specifically the bit about `chainL` is why I'm interested in using Parsley in the first place cause I ran into exactly this a while back trying to parse stuff in Elm via elm/parser. Ended up having to change my AST which was a major pain point.

**Comment by j-mie6** [comment]
I'm aware the `parsley-garnish` is broken on later GHC's (needs a rewrite), but not parsley itself. Let me check

**Comment by j-mie6** [comment]
Ah right, looks like I've just been too conservative with my bounds on 9.6: I can fix that on the currently published versions, but you might want to wait for me to get around to releasing the next version of `parsley-core` for stability updates.

I would recommend `gigaparsec`, if only it weren't a day old 😛. I'll just push the version stretch: if it works ok, I'll weaken the bounds on the older versions (after testing them, of course)

**Comment by j-mie6** [comment]
Ok, so `parsley-2.0.0.0` can happily widen the versions, but the current `parsley-core` published cannot work with 9.6. I'll try and make a release of core `2.3.0.0` as soon as I can :)

**Comment by j-mie6** [comment]
* [x] `parsley-2.0.0.1` released
* [ ] `parsley-core-2.3.0.0` released

**Comment by erlandsona** [comment]
Well hot dog! Glad I asked, thanks a ton!
