### ISSUE TITLE
More compilation instructions?

### ISSUE THREAD

**Issue by Kakadu** [j-mie6/ParsleyHaskell#9]
I tried to build Haskell projects only using Stack and this cabal-only approach is very alien to me. Could you, please, add compilation instructions, like compiler version and required dependencies?

**Comment by j-mie6** [comment]
I can do, but everything can be found inside the cabal file namely a list of the dependencies as well as the compiler version: 8.6.5.

**Comment by Kakadu** [comment]
By some reason I was looking only at `base` package` in .cabal file. But I got it compilable. The useful command should be

    stack exec --no-ghc-package-path --resolver=lts-14.27 -- cabal new-build

Thanks, for the quick answer

**Comment by j-mie6** [comment]
Good to know, thanks! I've never actually used stack before so it's useful to know it works.

**Comment by Kakadu** [comment]
Btw, when I run `stack exec --no-ghc-package-path --resolver=lts-14.27 -- cabal v2-haddock` I get the following. Is it an issue in my environment or in yours?

```
Build profile: -w ghc-8.6.5 -O2
In order, the following will be built (use -v for more details):
 - parsley-0.1.0.0 (file /media/oldhome/kakadu/prog/asp/ParsleyHaskell/dist-newstyle/build/x86_64-linux/ghc-8.6.5/idioms-plugin-0/opt/cache/build changed)
Preprocessing library for parsley-0.1.0.0..
Running Haddock on library for parsley-0.1.0.0..
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: constraints-0.12,
constraints-extras-0.3.0.2, dependent-map-0.4.0.0, dependent-sum-0.7.1.0,
ghc-tcplugins-extra-0.4.1, hashable-1.3.0.0, idioms-plugin-0,
lift-plugin-0.1.0.0, pretty-terminal-0.1.0.0, semigroups-0.19.1, some-1.0.1,
syb-0.7.2.1, transformers-compat-0.6.6, type-equality-1,
unordered-containers-0.2.13.0
Haddock coverage:

..................
src/Parsley/Applicative.hs:51:17: error:
    • No instance for (Language.Haskell.TH.Syntax.Lift
                         (a -> b -> (a, b)))
        arising from a use of ‘code’
        (maybe you haven't applied a function to enough arguments?)
    • In the first argument of ‘liftA2’, namely ‘(code (,))’
      In the expression: liftA2 (code (,))
      In an equation for ‘<~>’: (<~>) = liftA2 (code (,))
   |
51 | (<~>) = liftA2 (code (,))
   |                 ^^^^^^^^
Warning: Failed to build documentation for parsley-0.1.0.0.
```

**Comment by j-mie6** [comment]
Looks like the `Lift` plugin hasn't been applied? Ah. yeah, you need my fork of the lift and idioms plugins, the cabal usually sources them in my `cabal.project` file, which points at the correct commits
